version: '3.9'

services:
  camba-db:
    container_name: camba-db
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    restart: always
  camba-auth:
    container_name: camba-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - camba-db
    restart: always
volumes:
  mongo:
